export { default as Text } from '@/components/helpers/text';
export { default as Icon } from '@/components/helpers/icon';
export { default as Content } from '@/components/helpers/content';
export { default as Tab } from '@/components/helpers/tab';
export { default as Button } from '@/components/shared/button';
export { default as Tag } from '@/components/shared/tag';
export { default as Badge } from '@/components/shared/badge';
export { default as Tabs } from '@/components/shared/tabs';
export { default as Chekbox } from '@/components/shared/chekbox';
